### ISSUE TITLE
not starting up

### ISSUE THREAD

**Issue by vasyl-shumskyi** [nickbalestra/kactus#34]
Hello, 

Looks like `jekyll serve` erroring: 

```
kactus $ jekyll serve

/usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler (LoadError)
	from /usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.5.2/lib/jekyll/plugin_manager.rb:46:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.5.2/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by cjekel** [comment]
Is this a consequence of https://github.com/nickbalestra/kactus/issues/32 ? 

Edit: No this is an unrelated issue.

**Comment by cjekel** [comment]
I had this same issue. See https://stackoverflow.com/questions/35760407/whats-causing-jekyll-to-throw-a-undefined-method-require-from-bundler-error

What I did to fix the issue is uninstall jekyll
`$ sudo gem uninstall jekyll`
I had 4 different version installed. I uninstalled all of the versions. Then I ran
`$ sudo gem install jekyll blunder github-pages`
and now `jekyll build` and `jekyll serve` are working
